### ISSUE TITLE
Update for IPython 5.0

### ISSUE THREAD

**Issue by dtkerr** [tgoodlet/pytest-interactive#13]
The new prompts system in IPython 5.0 renders this unrunnable. Some other issues have prevented me getting a full PR for this, but the gist of what needs to change is that

```python
    pm = ipshell.prompt_manager
    bold_prmpt = '{color.number}' '{tt}' '{color.prompt}'
    pm.in_template = "'{}' selected >>> ".format(bold_prmpt)
    # don't rjustify with preceding 'in' prompt
    pm.justify = False
```

Needs to be replaced with the new crap, and the basics for how to replace the input prompt would be to add on to the plugin.py with something like:

```python
from IPython.terminal.prompts import Prompts, Token
...

class PytestPrompt(Prompts):
    def in_prompt_tokens(self, cli=None):
        return [
            (Token.Prompt, '{color.number}'),
            (Token.PromptNum, '{tt}'),
            (Token.Prompt, ' selected >>> '),
        ]


class PytestShellEmbed(InteractiveShellEmbed):
    """Custom ip shell with a slightly altered exit message
    """
    prompts_class = PytestPrompt
    ...
```

**Comment by tgoodlet** [comment]
Thanks @dtkerr!

Yeah looks like [this spot in the docs](http://ipython.readthedocs.io/en/stable/config/details.html#custom-prompts) is a good starting point to begin revamping the whole thing.

I've also wanted to take a look at fuzzy matching (#5) so playing with [`pythonpt`](http://python-prompt-toolkit.readthedocs.io/en/stable/) directly might be a good way to go as well.

**Comment by tgoodlet** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fAq0Kz9D&#x2F;1-pytest-interactive-to-new-ipython"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> pytest-interactive to new IPython</a>

**Comment by tgoodlet** [comment]
@dtkerr Think I nailed it.
Give it a try and let me know!
