### ISSUE TITLE
Integrate with the pytest cache

### ISSUE THREAD

**Issue by tgoodlet** [tgoodlet/pytest-interactive#15]
@moises-silva mentioned that it would be handy to have a way to get a failed test's id spec from inside the debugger such that you can rerun **just** that test easily in the next `pytest` invocation using that id.

I was thinking we could add a `pytest.get_test_id()` or something similar which could aid with this but I'd really love to find a more elegant solution.

**Comment by moises-silva** [comment]
@tgoodlet Another way that may not require a lot of changes is store that id in a tmpfile (eg $HOME/.pytest_failed_id) and then have a command line switch --retry for pytest (or pytest interactive plugin) that will read the id from there and re-run that test.

**Comment by tgoodlet** [comment]
@moises-silva turns out this is addressed in `pytest` 3.0 with the new [cache](http://doc.pytest.org/en/latest/cache.html) feature.

**Comment by moises-silva** [comment]
@tgoodlet that sounds pretty good to me
